### PR TITLE
Adds support for custom error pages handlers

### PR DESCRIPTION
**Pull request by lukaszbachman**

### CODE REVIEW

**Comment by andrus** [comment]
Hi @lukaszbachman . Thanks for this and the other pull requests. I like the ideas. Will start looking at them soon. In the meantime would you mind to fill and send me the CLA at http://bootique.io/cla/ ? Your contributions go far beyond trivial, so we'd like to keep the paperwork in order :) Thanks!

**Comment by lukaszbachman** [comment]
Hi @andrus, I submitted the CLA on July 12th, hope it didn't got lost in meantime ;)

**Comment by andrus** [comment]
@lukaszbachman Sorry, my bad. I even replied to you back then :) We are all set then.

**Comment by lukaszbachman** [comment]
@andrus great! Let me know if you have any comments about this PR so that I can adjust any further submissions to your code standards.

**Comment by andrus** [comment]
Merged. As far as coding standards go, I made a few minor changes:

* Replaced wildcard import with explicit imports.
* Removed dependency on Guava collections. While they come with Guice, I'd still like to keep our code free from this and other dependencies as much as possible. This gives us more freedom to change things in the future (we are thinking of gradually replacing the few core deps with internal implementations .. Not Guice yet, but who knows :)) I had to sacrifice immutability of `getErrorPages()`,  which I guess is consistent with the structure of the rest of the factory.

**Pull request merged**
